<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Error" Id="{3515e40d-777d-086e-1dc5-e25dbbabd80a}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ABSTRACT Error IMPLEMENTS I_Error
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Protected" Id="{887f3b17-8e31-0b5c-2d86-65ac4f391b4a}" />
    <Property Name="ErrorCode" Id="{443c9683-8c58-0776-1b0f-80ac57c3449b}">
      <Declaration><![CDATA[PROPERTY ABSTRACT ErrorCode : UDINT]]></Declaration>
      <Get Name="Get" Id="{02119e76-31be-01d2-02bf-96d7f11555ee}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Message" Id="{e2a32734-1d54-0a56-07cb-dfb54be1f349}">
      <Declaration><![CDATA[PROPERTY PUBLIC ABSTRACT Message : T_MAXSTRING]]></Declaration>
      <Get Name="Get" Id="{dc55775d-b2bb-0231-3138-de763b7ce1cb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="OnSerialize" Id="{824b0a20-902e-0d1e-1725-0a5ec5992781}" FolderPath="Protected\">
      <Declaration><![CDATA[METHOD PROTECTED OnSerialize
VAR_INPUT
	Serializer : I_Serializer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SerializeWith" Id="{10c32aab-be5b-02bb-0000-71a31e6df822}">
      <Declaration><![CDATA[METHOD PUBLIC SerializeWith
VAR_INPUT
	Serializer : I_Serializer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Serializer.StartObject();
Serializer.AddKeyString('message',Message);
Serializer.AddKeyUdint('errorCode',ErrorCode);
OnSerialize(Serializer);
Serializer.EndObject();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>