<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="NullError" Id="{b8ab4d0c-b8a6-0052-0e6f-01b4460fb7b3}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK NullError EXTENDS Error
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="ErrorType" Id="{866a1934-1b37-0d37-2c5f-39a9e12da41d}">
      <Declaration><![CDATA[PROPERTY ErrorType : T_MAXSTRING]]></Declaration>
      <Get Name="Get" Id="{d79e2093-a2fa-0b4a-1947-74c02242ac29}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Message" Id="{3c6a9af1-29d8-0186-089a-9274b1a3dbe7}">
      <Declaration><![CDATA[PROPERTY PUBLIC Message : T_MAXSTRING]]></Declaration>
      <Get Name="Get" Id="{5ff9de6b-ecd5-0d62-2807-c1189cb0788b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="SerializeWith" Id="{644a06b5-1950-0abc-35a7-7924bce9d81c}">
      <Declaration><![CDATA[METHOD PUBLIC SerializeWith
VAR_INPUT
	Serializer : I_Serializer;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>