<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f1f17182-c532-44e8-9b09-d7890d036169}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	error_TestSuite : Error_TestSuite;
	nullError_TestSuite : NullError_TestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>